"""empty message

Revision ID: b90e8709dd45
Revises: cc4c536c1e48
Create Date: 2023-03-17 21:47:29.917740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b90e8709dd45'
down_revision = 'cc4c536c1e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('path_foto',
               existing_type=mysql.VARCHAR(length=12),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('path_foto',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###
