"""empty message

Revision ID: bb24f6e1bf1e
Revises: b90e8709dd45
Create Date: 2023-03-17 23:07:24.001998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb24f6e1bf1e'
down_revision = 'b90e8709dd45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=250), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('name_author', sa.String(length=50), nullable=True),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default='<built-in method utcnow of type object at 0x00007FFEA3A18980>', nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('depto_no', sa.String(length=12), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=mysql.VARCHAR(length=9),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=9),
               existing_nullable=True)

    op.drop_table('claims')
    # ### end Alembic commands ###
