"""empty message

Revision ID: cc4c536c1e48
Revises: 5950b9f9a099
Create Date: 2023-03-17 21:46:14.899764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4c536c1e48'
down_revision = '5950b9f9a099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_foto', sa.String(length=12), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('path_foto')

    # ### end Alembic commands ###
