"""empty message

Revision ID: f1803eb8cbf0
Revises: 71c3e1af760a
Create Date: 2023-03-17 20:19:13.595469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1803eb8cbf0'
down_revision = '71c3e1af760a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=250), nullable=True))
        batch_op.drop_column('nombre')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('nombre', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
